//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asistencia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class    Asistente
    {
        public int IntIdAsistente { get; set; }
        [Required(ErrorMessage = "El nombre es requerido")]
        [StringLength(200, ErrorMessage = "Máximo 200 caracteres")]
        public string strNombre { get; set; }
        [Required(ErrorMessage = "El cargo es requerido")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string strCargo { get; set; }
        public int intIdEvento { get; set; }
        [Required(ErrorMessage = "La sección es requerida")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string strSeccion { get; set; }
        [Required(ErrorMessage = "La firma es obligatoria")]
        [UIHint("SignaturePad")]
        public byte[] binFirma { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
