//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asistencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistente
    {
        public int IntIdAsistente { get; set; }
        public string strNombre { get; set; }
        public string strCargo { get; set; }
        public byte[] btyFirma { get; set; }
        public int intIdEvento { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
