//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asistencia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Asistente
    {
        public int IntIdAsistente { get; set; }
        [Required(ErrorMessage = "El nombre es requerido")]
        [StringLength(200, ErrorMessage = "Máximo 200 caracteres")]
        public string strNombre { get; set; }
        [Required(ErrorMessage = "El cargo es requerido")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string strCargo { get; set; }
        public int intIdEvento { get; set; }
        [Required(ErrorMessage = "La sección es requerida")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string strSeccion { get; set; }
        [Required(ErrorMessage = "La firma es requerida")]
        [UIHint("SignaturePad")]
        public byte[] binFirma { get; set; }
        [Required(ErrorMessage = "El documento es requerido")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string strDocumento { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
