//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asistencia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.Asistentes = new HashSet<Asistente>();
        }

        public int intIdEvento { get; set; }
        [Required(ErrorMessage = "El tema es requerido")]
        [StringLength(200, ErrorMessage = "Máximo 200 caracteres")]
        public string strTema { get; set; }
        [Required(ErrorMessage = "El facilitador es requerido")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string strFacilitador { get; set; }
        [Required(ErrorMessage = "El lugar es requerido")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string strLugar { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Required(ErrorMessage = "La fecha es requerida")]
        public System.DateTime dtmFecha { get; set; }
        [DataType(DataType.Time)]
        [Required(ErrorMessage = "La duración es requerida")]
        public System.TimeSpan dtmDuracion { get; set; }
        public bool bitEstado { get; set; }
        public int intCreador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistente> Asistentes { get; set; }
    }
}
