//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asistencia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Usuario_Rol = new HashSet<Usuario_Rol>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "El nombre es requerido")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string Nombres { get; set; }
        [Required(ErrorMessage = "El apellido es requerido")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string Apellidos { get; set; }
        [EmailAddress]
        [Required(ErrorMessage = "El correo es requerido")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string Email { get; set; }
        [Required(ErrorMessage = "La clave es requerida")]
        public string Clave { get; set; }
        public string ProviderKey { get; set; }
        public string ProviderName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Rol> Usuario_Rol { get; set; }
    }
}
